### ISSUE TITLE
1 out of 1 hunk FAILED -- saving rejects to file fs/ksmbd/smb2misc.c.rej

### ISSUE THREAD

**Issue by AldairSoraka** [ptr1337/kernel-patches#1]
When i try to compile a kernel with ksmbd patch give that error, someone know a fix?, Meanwhile I will exclude it from my kernel build

**Comment by ptr1337** [comment]
> When i try to compile a kernel with ksmbd patch give that error, someone know a fix?, Meanwhile I will exclude it from my kernel build

Will be fixed with upcoming 5.15.3 kernel. ive already updated the patches. Next time i will create a new branch for the next kernel version. Was a issue at my side.

Will be released today: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/

**Comment by ptr1337** [comment]
fixed with kernel 5.15.3

> When i try to compile a kernel with ksmbd patch give that error, someone know a fix?, Meanwhile I will exclude it from my kernel build
